# errata:
# - sudo/dist/group are set so as to get Blue Box VMs, necessary for [loopback]
#   IPv6 support

sudo: required
dist: bionic

os: linux
language: minimal

services:
  - docker

cache:
  ccache: true
  directories:
    - $HOME/cache

env:
  global:
    # DOCKER_HUB_USER
    - secure: "egvce4tWb5UzHfhEPJySZP5rb4p7MOh73BB0PKT/qSUXCtddBpjpmdiNxvUiQS4NwrEvzDarwA9zAIlSqxXx9xLhANZnQusFxnlRWF+BU/BVCpTNP4Ns5twGGthD2x5MWy3WtueOAkULv9nOJU1A8/ocHJQS2hVK2GqhfUuF+18CZ7kvqgGY1jplanqh0iijAc2re+cvnzqCd76hWVlvOWlvzwIJW7qUmzHLs/ggZ24uemd1tlkkRZoHJpb48I0bY0I8qOBMOGWTqZ5bd4Fu3BfKznG/k/kDflsWLiuL8tu9SBzNGlFPMpKLqSt4KdB9/+X/B9XZjuIyNvJOWA5i9sbt2YUIdQ81IGsI+RWxIQ/59r5bXnBHaira2/U4Vqil2oHff7KDNklRDXp30a/DYZInjuKtPJyvhaSW0Kr/ZSmbIG14ygOT3axNAWarZDvtXaU3I0IsI1SeILLYoB0mhen/Wad2I8o6eXHlGsBmGN8qz1r5u3tS9ePs1pUFdq5yKVNxe8/kiMQk2tqJCuhQ45xy/hKfBD90QSI7Jf9aqAVjBpUaQ8SWFmaF348l9UMoGpLtmSihcgQCxB1K6tQbebnL99Sc4WsrMlMqjtF1P3qsPG7KS2ECCHrKlC4DyMeWIlDyadi6JU/CR6W2dLzzjI42wUIFiLyf5pypoajVKDU="
    # DOCKER_HUB_PASSWORD
    - secure: "MDUt28ob1jvXCALxbWgkoUyxgRS40Yoq7VZVHE0+w+CLO9Z1+G/snd+VHJmHR2XChk7MGRIjzfU6nvW+rKhabKgEYXm1Wn1W2/MiKV+J8hqZEq892kZQxM3lxc1v0Q9qMThT4JaBlHwDBkUE2xqFe9toNiIhxJttq3yYoCHArg76uSpVVANRxaIXtbrDd0kur64bHnWSqJDf/hg7GP+u0rEwqMCBLKW9kcL6HbCAOZa4o6M6571vXGyHwUgBK+TQxxwigkj5Uhnq5iNwLhaBMaCxeyvXgtq+H8JkIxfsmpuCm6eSIWUp22opsJuvLWGsX1oG3Zu2pG2f/VfS4+fiXyBbuHP9in1LtysJm7/Xl2YWXWkgajgJ1cOVOg+fmimeXQmWKn3yO5DdsKfpYKaaV2CNcqSxTsl7zhnksSHcoVMs73+Rc2NTtGweQ/VbuiDl5DQFRQdXsT5aW6QhWWd3/2i5HOtximIz36gmab1JuU7ohQuvb1dRcbS04+W9HLsHEPy90YzwePOuIYpmE1lLRCZs5Fn8f6blqhX7d+4s8FUn7DpZwnnxOLWRqqVeY39GWd0SiRSoHPCKgFXQCUnfogEBj5xRBO6RW8cq8cD7Aja4CeuRG12ghnNM0hOpKlZFxmyhRX1N58JSZshLphGb+0o6CVhiPWa9oA5Ms0FaowQ="
    - DOCKER_BUILD=false

stages:
  - build docker

builddocker: &builddocker
  stage: build docker
  script:
    # no need to run tests again here
    - if [ "$DOCKER_BUILD" = "true" ]; then $DOCKER_RUN_IN_BUILDER ./ci/build_depends.sh && $DOCKER_RUN_IN_BUILDER ./ci/build_src.sh && BUILD_DIR=build-ci/axecore-$BUILD_TARGET ./docker/build-docker.sh; fi

jobs:
  include:
    # build docker
    - <<: *builddocker
      env: BUILD_TARGET=linux64_release DOCKER_BUILD=true

before_cache:
  # Save builder image
  - docker save axe-builder-$BUILD_TARGET-$TRAVIS_JOB_NUMBER $(docker history -q axe-builder-$BUILD_TARGET-$TRAVIS_JOB_NUMBER | grep -v \<missing\>) | gzip -2 > $HOME/cache/docker/axe-builder-$BUILD_TARGET.tar.gz

install:
    # Fix annoying Travis bug: a branch with a single commit has an empty TRAVIS_COMMIT_RANGE sometimes
    - if [ -z "$TRAVIS_COMMIT_RANGE" ]; then export TRAVIS_COMMIT_RANGE="HEAD~..HEAD"; fi
    # Our scripts try to be Travis agnostic
    - export PULL_REQUEST="$TRAVIS_PULL_REQUEST"
    - export COMMIT_RANGE="$TRAVIS_COMMIT_RANGE"
    - export JOB_NUMBER="$TRAVIS_JOB_NUMBER"
    - export HOST_SRC_DIR=$TRAVIS_BUILD_DIR
    - export HOST_CACHE_DIR=$HOME/cache
    - export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
    - export PYTHON_DEBUG=1
    - source ./ci/matrix.sh
    - mkdir -p $HOST_CACHE_DIR/docker && mkdir -p $HOST_CACHE_DIR/ccache && mkdir -p $HOST_CACHE_DIR/depends && mkdir -p $HOST_CACHE_DIR/sdk-sources
    # Keep this as it makes caching related debugging easier
    - ls -lah $HOST_CACHE_DIR && ls -lah $HOST_CACHE_DIR/depends && ls -lah $HOST_CACHE_DIR/ccache && ls -lah $HOST_CACHE_DIR/docker
    # Load cached builder image
    - if [ -f $HOST_CACHE_DIR/docker/axe-builder-$BUILD_TARGET.tar.gz ]; then zcat $HOST_CACHE_DIR/docker/axe-builder-$BUILD_TARGET.tar.gz | docker load || true; fi
    - travis_retry docker pull ubuntu:bionic
    - travis_retry docker build -t $BUILDER_IMAGE_NAME --build-arg=USER_ID=$UID --build-arg=GROUP_ID=$UID --build-arg=BUILD_TARGET=$BUILD_TARGET -f ci/Dockerfile.builder ci
before_script:
    # Make sure stdout is in blocking mode. Otherwise builds will fail due to large writes to stdout
    # See https://github.com/travis-ci/travis-ci/issues/4704. If this gets fixed, this line can also be removed.
    - python3 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
    # Build docker image only for development branch of the main repo
    - echo TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG
    - echo TRAVIS_BRANCH=$TRAVIS_BRANCH
    - echo TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST
    - echo DOCKER_BUILD=$DOCKER_BUILD
    - if [ "$TRAVIS_REPO_SLUG" != "axerunners/axe" -o "$TRAVIS_BRANCH" != "development" -o "$TRAVIS_PULL_REQUEST" != "false" ]; then export DOCKER_BUILD="false"; echo DOCKER_BUILD=$DOCKER_BUILD; fi
after_script:
    - echo $TRAVIS_COMMIT_RANGE
    - echo $TRAVIS_COMMIT_LOG
after_success:
    - if [ "$DOCKER_BUILD" = "true" ]; then docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD && ./docker/push-docker.sh; fi
